name: Update AREDL site

on:
  schedule:
    - cron: '0 * * * *'  # every Hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: clone Repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: run script
      run: python import_requests.py

      
    - name: push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html
        git commit -m "automatically updated html file" || echo "No Changes to Commit"
        git push origin main
