name: Update AREDL site

on:
  schedule:
    - cron: '0 * * * *'  # every Hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: clone Repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: run script
      run: python import_requests.py

      
    - name: commit and push changes
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "action@github.com"  
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --cached --quiet || git commit -m "Automatisches Update der Seite"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:main
